// 引入 Bootstrap 的樣式檔案
import "bootstrap/dist/css/bootstrap.min.css";

// 引入全域樣式
import "../styles/globals.css";

import { useEffect } from "react";
import Head from "next/head";

export default function MyApp({ Component, pageProps }) {
  // 引入 Bootstrap 的程式碼檔案
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
